eclipse-workspace/Surya Dev Org/src/objects/Account_Info__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Opened_On__c</fullName>
        <label>Account Opened On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Info</label>
    <nameField>
        <displayFormat>ACC-{0000000000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/objects/Credit_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Info</label>
        <referenceTo>Account_Info__c</referenceTo>
        <relationshipLabel>Credit History</relationshipLabel>
        <relationshipName>Credit_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Credit Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Loan?</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit History</label>
    <nameField>
        <displayFormat>SSN-{000000000}</displayFormat>
        <label>SSN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Info__c</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Loan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit History</label>
        <referenceTo>Credit_History__c</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Loan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Holder_Name__c</fullName>
        <label>Loan Holder Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Auto Loan</fullName>
                </value>
                <value>
                    <fullName>Mortgage Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/objects/Transaction_History__c.object
<CustomObject>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transferred_On__c</fullName>
        <label>Transferred On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transferred_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transferred to</label>
        <referenceTo>Account_Info__c</referenceTo>
        <relationshipLabel>Transaction History</relationshipLabel>
        <relationshipName>Transaction_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction History</label>
    <nameField>
        <displayFormat>TN-{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/classes/BankingListController.cls
public with sharing class BankingListController {
    @AuraEnabled
    public static List<Account_Info__c> getAccountInfo() {
        return[select id, Name, Account_Name__c, Account_Type__c, Account_Opened_On__c
                					from Account_Info__c
                					ORDER BY createdDate ASC]; 
    }
    @AuraEnabled
    public static List<Transaction_History__c> getTransactionInfo() {
        return[select id, Name, Transaction_Status__c, Transferred_On__c, Transferred_to__c,Transferred_to__r.Name
                					from Transaction_History__c
                					ORDER BY createdDate ASC]; 
    }
    @AuraEnabled
    public static List<Loan__c> getLoanInfo() {
        return[select id, Name, Account_Number__c, Credit_History__c, Loan_Holder_Name__c, Loan_Type__c, Account_Number__r.Name,Credit_History__r.Name
                					from Loan__c
                					ORDER BY createdDate ASC]; 
    }
    @AuraEnabled
    public static List<Credit_History__c> getCreditInfo() {
        return[select id, Name, Account_Info__c, Credit_Score__c, Eligible_for_Loan__c, Account_Info__r.Name
                					from Credit_History__c
                					ORDER BY createdDate ASC]; 
    }
}