eclipse-workspace/Surya Dev Org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CalculateTime__c</fullName>
        <description>To calculate Time</description>
        <formula>if(((NOW() -  CreatedDate)*24)&lt;=2,&apos;&lt; 2 Hrs&apos;,if(((NOW() -  CreatedDate)*24)&lt;=4,&apos;&lt; 4 Hrs&apos;,if(((NOW() -  CreatedDate)*24)&lt;=6,&apos;&lt; 6 Hrs&apos;,if(((NOW() -  CreatedDate)*24)&lt;=24,&apos;&gt; 8 Hrs&apos;,if(((NOW() -  CreatedDate)*24)&lt;=24*5,&apos;&gt; 1 day&apos;,if(((NOW() -  CreatedDate)*24)&gt;=24*5,&apos;&gt; 5 days&apos;,&apos;&apos;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Time Filter</inlineHelpText>
        <label>CalculateTime</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Stage__c</fullName>
        <label>Sub Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity Validation Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/classes/c3.cls
public class c3{

    Account[] selectedacts;
    Opportunity[] selectedopts;
    
    public Account[] getselectedacts(){
        return selectedacts;
    }
    public Opportunity[] getselectedopts(){
    return selectedopts;
    }
    
    public pagereference showall(){
    selectedacts= [select Name, Type, Industry, Phone, Fax from Account];
    return null;
    }
    public pagereference showfiltered(){
    selectedacts= [select Name, Type, Industry, Phone, Fax from Account where Type='Customer - Channel'];
    return null;
    }
        
    public pagereference oppshowall(){
    selectedopts= [select Name, Amount, Probability, CalculateTime__c,Sub_Stage__c from Opportunity];
    return null;
    }
    public pagereference oppshowfiltered(){
    selectedopts= [select Name, Amount, Probability, CalculateTime__c,Sub_Stage__c from Opportunity where CalculateTime__c > '> 5 days'];
    return null;
    }
}