eclipse-workspace/Surya Dev Org/src/objects/ZTS_Events__c.object
<CustomObject>
    <fields>
        <fullName>ZTS_US_Event_Category__c</fullName>
        <description>Zoetis</description>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>Educational Meeting</fullName>
                </value>
                <value>
                    <fullName>Philanthropy</fullName>
                </value>
                <value>
                    <fullName>Premium Services</fullName>
                </value>
                <value>
                    <fullName>Relationship Building</fullName>
                </value>
                <value>
                    <fullName>Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Value Added Services</fullName>
                </value>
                <value>
                    <fullName>Poultry Events</fullName>
                </value>
                <value>
                    <fullName>Marketing Meeting</fullName>
                </value>
                <value>
                    <fullName>Speaker Event – Online Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZTS_US_Location__c</fullName>
        <description>Zoetis</description>
        <label>Location</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ZTS_US_Name__c</fullName>
        <description>zoetis</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZTS_US_Type__c</fullName>
        <description>Zoetis</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ZTS_US_Event_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>BRD Solutions</fullName>
                </value>
                <value>
                    <fullName>Breeding Soundness Exams (BSE)</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Calf &amp; Heifer Solutions</fullName>
                </value>
                <value>
                    <fullName>Cash Donations</fullName>
                </value>
                <value>
                    <fullName>Cattle General</fullName>
                </value>
                <value>
                    <fullName>Charitable Event</fullName>
                </value>
                <value>
                    <fullName>Continuing Education Support</fullName>
                </value>
                <value>
                    <fullName>Contract Distributor Programs</fullName>
                </value>
                <value>
                    <fullName>Cooperative Advertising</fullName>
                </value>
                <value>
                    <fullName>Customer surveys (DRC)</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
                <value>
                    <fullName>Employee Training</fullName>
                </value>
                <value>
                    <fullName>Equine General</fullName>
                </value>
                <value>
                    <fullName>EquineInternalParaContrl</fullName>
                </value>
                <value>
                    <fullName>Equine Lameness</fullName>
                </value>
                <value>
                    <fullName>ES - Equine Customer Meeting</fullName>
                </value>
                <value>
                    <fullName>ES - Equine Vet Meeting</fullName>
                </value>
                <value>
                    <fullName>FRANK</fullName>
                </value>
                <value>
                    <fullName>Full Day Wet Lab</fullName>
                </value>
                <value>
                    <fullName>Genomics</fullName>
                </value>
                <value>
                    <fullName>Half Day Wet Lab</fullName>
                </value>
                <value>
                    <fullName>Impromptu event</fullName>
                </value>
                <value>
                    <fullName>In Clinic/hospital</fullName>
                </value>
                <value>
                    <fullName>In Clinic Promotional Material</fullName>
                </value>
                <value>
                    <fullName>Information Sharing</fullName>
                </value>
                <value>
                    <fullName>IPC – Event (Pork Only)</fullName>
                </value>
                <value>
                    <fullName>Join the Cause</fullName>
                </value>
                <value>
                    <fullName>Large Group Roundtable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Events</label>
    <nameField>
        <displayFormat>EVE-{0000}</displayFormat>
        <label>Events Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/objects/ZTS_US_Event_Invitee__c.object
<CustomObject>
    <description>Acts as a Junction between Contacts and Events

Zoetis Client</description>
    <fields>
        <fullName>ZTS_US_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events Attended</relationshipLabel>
        <relationshipName>Invitees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZTS_US_Event__c</fullName>
        <description>Zoetis</description>
        <label>Events</label>
        <referenceTo>ZTS_Events__c</referenceTo>
        <relationshipLabel>Event Invitees</relationshipLabel>
        <relationshipName>Invitees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Event Invitee</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invitee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Invitees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/Surya Dev Org/src/classes/CEEventUpdateAttendeeStatusTest.cls
@isTest
private class CEEventUpdateAttendeeStatusTest {

    static testMethod void performUpdateTest(){
        //create ZTS_Events__c record, please include if any mandatory fields are missing 
        ZTS_Events__c ztsEvent = new ZTS_Events__c(ZTS_US_Location__c = 'Test Location',
                    //ZTS_US_Type__c is dependent picklist on ZTS_US_Event_Category__c field. So assign the correct values accordingly to these fields.
                                                   ZTS_US_Event_Category__c = 'Test Category', 
                                                   ZTS_US_Type__c = 'Test Category',
                                                   ZTS_US_Name__c   = 'Alex'
                                                   //ZTS_US_Contact__c= 'Test'
                                                );
        insert ztsEvent;
        
        Contact c= new Contact(LastName = 'Test');
        insert c;
        
        //create some ZTS_US_Event_Invitee__c records with ztsEvent as paernt, please include if any mandatory field are missing 
        List<ZTS_US_Event_Invitee__c> inviteeList = new List<ZTS_US_Event_Invitee__c>();
        inviteeList.add(new ZTS_US_Event_Invitee__c(ZTS_US_Event__c=ztsEvent.Id,ZTS_US_Contact__c=c.Id));
        inviteeList.add(new ZTS_US_Event_Invitee__c(ZTS_US_Event__c=ztsEvent.Id,ZTS_US_Contact__c=c.Id));
        inviteeList.add(new ZTS_US_Event_Invitee__c(ZTS_US_Event__c=ztsEvent.Id,ZTS_US_Contact__c=c.Id));
        inviteeList.add(new ZTS_US_Event_Invitee__c(ZTS_US_Event__c=ztsEvent.Id,ZTS_US_Contact__c=c.Id));
        insert inviteeList;
        
        ApexPages.StandardController stdZtsEvent = new ApexPages.StandardController(ztsEvent);          
        CEEventUpdateAttendeeStatus ceUpdateController = new CEEventUpdateAttendeeStatus(stdZtsEvent);
        
        ceUpdateController.wrpConList[0].isSelected = true;
        
        ceUpdateController.selectAllVar = false;

        ceUpdateController.selectAll();
        ceUpdateController.updateStatus();
        
        ceUpdateController.selectAllVar = true;

        ceUpdateController.selectAll();
        ceUpdateController.updateStatus();
        ceUpdateController.cancelAction();
    }
    
   static testMethod void performUpdateTestNegetive(){
        //create ZTS_Events__c record, please include if any mandatory fields are missing 
        ZTS_Events__c ztsEvent = new ZTS_Events__c(ZTS_US_Location__c = 'Test Location',
                    //ZTS_US_Type__c is dependent picklist on ZTS_US_Event_Category__c field. So assign the correct values accordingly to these fields.
                                                   ZTS_US_Event_Category__c = 'Test Category', 
                                                   ZTS_US_Type__c = 'Test Category',
                                                   ZTS_US_Name__c   = 'Alex'
                                                   //ZTS_US_Contact__c= 'Test'
                                                );
        insert ztsEvent;
        
        Contact c= new Contact(LastName = 'Test');
        insert c;
        
        ApexPages.StandardController stdZtsEvent = new ApexPages.StandardController(ztsEvent);          
        CEEventUpdateAttendeeStatus ceUpdateController = new CEEventUpdateAttendeeStatus(stdZtsEvent);
        
        ceUpdateController.selectAll();
        ceUpdateController.updateStatus();
        ceUpdateController.cancelAction();
    }
}